Repository Satellite-im/automated-tests-web, pull requests merged in 2024-06, with the labels that each got.

#22 test(add): add tests and increase timeout
  cypress.config.ts
  cypress/e2e/02-friends.cy.ts
  cypress/e2e/04-marketplace.cy.ts
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/06-settings-invetory.cy.ts
  cypress/e2e/07-settings-customization.cy.ts
  cypress/e2e/08-settings-messages.cy.ts
  cypress/e2e/09-settings-audio-video.cy.ts
  cypress/e2e/10-settings-extensions.cy.ts
  cypress/e2e/11-settings-keybindings.ts
  cypress/e2e/12-settings-notifications.cy.ts
  cypress/e2e/13-settings-about.cy.ts
  cypress/e2e/14-settings-license.cy.ts
  cypress/e2e/15-settings-developer-mode.cy.ts
  cypress/e2e/16-chats-tests.cy.ts
  cypress/e2e/17-wallet.cy.ts
  cypress/e2e/18-files.cy.ts
  cypress/e2e/19-files-sidebar.cy.ts
  cypress/e2e/PageObjects/AuthNewAccount.ts
  cypress/e2e/PageObjects/Friends.ts
  cypress/support/commands.ts
Labels: Missing dev review, invalid PR title

#23 test(add): add remaining settings profile tests
  .github/workflows/lint-PR-title.yml
  cypress/e2e/01-pin-input.cy.ts
  cypress/e2e/03-chats-sidebar.cy.ts
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/PageObjects/AuthNewAccount.ts
  cypress/e2e/PageObjects/ChatsMain.ts
  cypress/e2e/PageObjects/Settings/SettingsProfile.ts
Labels: Missing dev review, invalid PR title

#25 chore(cypress): clean indexdb before every test
  .github/workflows/automated-tests.yml
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/PageObjects/LoginPin.ts
Labels: Missing dev review

#24 add(test): add tests and po for several settings pages
  cypress/e2e/PageObjects/AuthNewAccount.ts
  cypress/e2e/PageObjects/Settings/SettingsCustomizations.ts
  cypress/e2e/PageObjects/Settings/SettingsInventory.ts
  cypress/e2e/PageObjects/Settings/SettingsMessages.ts
Labels: Missing dev review

#26 add(test): add tests for settings inventory
  cypress/e2e/06-settings-invetory.cy.ts
  cypress/e2e/PageObjects/Settings/SettingsInventory.ts
Labels: Missing dev review

#27 update(refactor): use base classes for settings and main pages
  .gitignore
  cypress/e2e/01-pin-input.cy.ts
  cypress/e2e/02-friends.cy.ts
  cypress/e2e/03-chats-sidebar.cy.ts
  cypress/e2e/04-marketplace.cy.ts
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/06-settings-inventory.cy.ts
  cypress/e2e/PageObjects/AuthNewAccount.ts
  cypress/e2e/PageObjects/ChatsMain.ts
  cypress/e2e/PageObjects/Friends.ts
  cypress/e2e/PageObjects/LoginPin.ts
  cypress/e2e/PageObjects/MainPage.ts
  cypress/e2e/PageObjects/PreLoading.ts
  cypress/e2e/PageObjects/Settings/SettingsBase.ts
  cypress/e2e/PageObjects/Settings/SettingsCustomizations.ts
  cypress/e2e/PageObjects/Settings/SettingsInventory.ts
  cypress/e2e/PageObjects/Settings/SettingsMessages.ts
  cypress/e2e/PageObjects/Settings/SettingsProfile.ts
Labels: Missing dev review

#31 chore(cypress): fix typo
  cypress/e2e/05-settings-profile.cy.ts
Labels: Missing dev review

#30 chore(cypress): suggestions on docs
  README.md
Labels: Missing dev review

#29 chore(cypress): update to latest
  package-lock.json
  package.json
Labels: Missing dev review

#33 chore(cypress): minor suggestions
  cypress/e2e/03-chats-sidebar.cy.ts
Labels: Missing dev review

#32 chore(cypress): minor updates
  cypress/e2e/01-pin-input.cy.ts
Labels: Missing dev review

#28 test(update): add tests for settings customizations
  cypress/e2e/02-friends.cy.ts
  cypress/e2e/03-chats-sidebar.cy.ts
  cypress/e2e/04-marketplace.cy.ts
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/06-settings-inventory.cy.ts
  cypress/e2e/07-settings-customization.cy.ts
  cypress/e2e/08-settings-messages.cy.ts
  cypress/e2e/PageObjects/AuthNewAccount.ts
  cypress/e2e/PageObjects/MainPage.ts
  cypress/e2e/PageObjects/Settings/SettingsBase.ts
  cypress/e2e/PageObjects/Settings/SettingsCustomizations.ts
  cypress/e2e/PageObjects/Settings/SettingsInventory.ts
  cypress/e2e/PageObjects/Settings/SettingsMessages.ts
Labels: Missing dev review

#35 chore(cypress): minor suggestions
  cypress/e2e/06-settings-inventory.cy.ts
Labels: Missing dev review

#36 chore(cypress): minor cypress suggestion
  cypress/e2e/07-settings-customization.cy.ts
  cypress/support/commands.ts
Labels: Missing dev review

#13 chore(playwright): draft to test playwright framework
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  playwright/example.spec.ts
Labels: Missing dev review, draft

#38 add(pageobjects): add page object ui element locators for settings
  cypress/e2e/PageObjects/Settings/SettingsAbout.ts
  cypress/e2e/PageObjects/Settings/SettingsAccessibility.ts
  cypress/e2e/PageObjects/Settings/SettingsAudio.ts
  cypress/e2e/PageObjects/Settings/SettingsDeveloper.ts
  cypress/e2e/PageObjects/Settings/SettingsExtensions.ts
  cypress/e2e/PageObjects/Settings/SettingsKeybinds.ts
  cypress/e2e/PageObjects/Settings/SettingsLicenses.ts
  cypress/e2e/PageObjects/Settings/SettingsNetwork.ts
  cypress/e2e/PageObjects/Settings/SettingsNotifications.ts
  cypress/support/commands.ts
Labels: Missing dev review

#40 update(pageobjects): update settings page objects
  cypress/e2e/PageObjects/Settings/SettingsAudio.ts
  cypress/e2e/PageObjects/Settings/SettingsBase.ts
  cypress/e2e/PageObjects/Settings/SettingsDeveloper.ts
  cypress/e2e/PageObjects/Settings/SettingsExtensions.ts
  cypress/e2e/PageObjects/Settings/SettingsKeybinds.ts
  cypress/e2e/PageObjects/Settings/SettingsLicenses.ts
  cypress/e2e/PageObjects/Settings/SettingsNetwork.ts
Labels: Missing dev review

#41 update(test): change scramble keypad disable by default
  cypress/e2e/01-pin-input.cy.ts
Labels: Missing dev review

#43 add(test): add test for settings keybinds
  cypress/e2e/11-settings-keybindings.cy.ts
  cypress/e2e/11-settings-keybindings.ts
  cypress/e2e/PageObjects/Settings/SettingsKeybinds.ts
Labels: Missing dev review

#44 add(test): tests for settings notifications about license accesibility
  cypress/e2e/12-settings-notifications.cy.ts
  cypress/e2e/13-settings-about.cy.ts
  cypress/e2e/14-settings-license.cy.ts
  cypress/e2e/16-settings-accessibility.cy.ts
  cypress/e2e/PageObjects/Settings/SettingsAccessibility.ts
Labels: Missing dev review

#45 update(test): fixes to tests applied by changes to settings
  cypress/e2e/13-settings-about.cy.ts
  cypress/e2e/14-settings-license.cy.ts
  cypress/e2e/PageObjects/Settings/SettingsAbout.ts
Labels: Missing dev review

#46 add(test): add tests for settings developer
  cypress/e2e/15-settings-developer-mode.cy.ts
  cypress/e2e/15-settings-developer.cy.ts
  cypress/e2e/PageObjects/Settings/SettingsDeveloper.ts
Labels: Missing dev review

#48 add(files): files page object and tests
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/20-files.cy.ts
  cypress/e2e/PageObjects/Files.ts
  cypress/e2e/PageObjects/MainPage.ts
Labels: Missing dev review

#47 update(test): skip tests for mobile animations bug
  cypress/e2e/03-chats-sidebar.cy.ts
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/07-settings-customization.cy.ts
  cypress/e2e/16-settings-accessibility.cy.ts
Labels: Missing dev review

#52 update(test): fix tests
  cypress/e2e/01-pin-input.cy.ts
  cypress/e2e/03-chats-sidebar.cy.ts
  cypress/e2e/05-settings-profile.cy.ts
  cypress/e2e/07-settings-customization.cy.ts
  cypress/e2e/16-settings-accessibility.cy.ts
  cypress/e2e/20-files.cy.ts
  cypress/e2e/PageObjects/LoginPin.ts
  cypress/e2e/PageObjects/MainPage.ts
  cypress/support/commands.ts
Labels: Missing dev review

#51 chore(cypress): minor suggestions
  cypress/e2e/13-settings-about.cy.ts
Labels: Missing dev review

#53 add(tests): add files tests
  cypress/e2e/20-files.cy.ts
  cypress/e2e/PageObjects/Files.ts
Labels: Missing dev review

#54 add(test): add more tests for files section
  cypress/e2e/20-files.cy.ts
  cypress/e2e/PageObjects/Files.ts
  cypress/e2e/PageObjects/MainPage.ts
Labels: Missing dev review

#55 add(test): add pom draft test for playwright
  .github/workflows/playwright.yml
  playwright.config.ts
  playwright/01-pin-input.spec.ts
  playwright/PageObjects/AuthNewAccount.ts
  playwright/PageObjects/ChatsMain.ts
  playwright/PageObjects/LoginPin.ts
  playwright/PageObjects/MainPage.ts
  playwright/example.spec.ts
Labels: Missing dev review
